"""
Patch: Standardise logo usage across CasaModerna print formats.

- Customer-facing (Quotation, Sales Order, Sales Invoice, Proforma, POS Invoice, Receipt):
  branded header with embedded base64 logo.
- Internal (Delivery Note): no logo; plain text company name only.
"""
from __future__ import annotations
import base64
import re
import frappe


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _logo_data_url() -> str:
    logo_path = frappe.get_site_path("public", "files", "cm-logo-print.png")
    with open(logo_path, "rb") as f:
        b64 = base64.b64encode(f.read()).decode()
    return f"data:image/png;base64,{b64}"


def _branded_header_css() -> str:
    return (
        "<style>\n"
        "*{box-sizing:border-box;margin:0;padding:0}\n"
        "body{font-family:Arial,Helvetica,sans-serif;font-size:10pt;color:#222;line-height:1.45}\n"
        ".pf-head{display:flex;justify-content:space-between;align-items:flex-start;"
        "border-bottom:3px solid #339966;padding-bottom:9px;margin-bottom:14px}\n"
        ".pf-company{display:flex;align-items:center;gap:12px}\n"
        ".pf-logo{height:55px;max-width:190px;object-fit:contain}\n"
        ".pf-company-name{font-size:11pt;font-weight:700;color:#339966}\n"
        ".pf-company-addr{font-size:8pt;color:#555;margin-top:2px}\n"
        ".pf-company-vat{font-size:7.5pt;color:#888;margin-top:1px}\n"
        ".pf-docbox{text-align:right}\n"
        ".pf-doctype{font-size:13pt;font-weight:700;color:#339966;text-transform:uppercase;letter-spacing:.5px}\n"
        ".pf-docno{font-size:11pt;font-weight:700;margin-top:1px}\n"
        ".pf-docmeta{font-size:8.5pt;color:#666;margin-top:2px}\n"
        ".pf-footer{margin-top:16px;padding-top:8px;border-top:1px solid #c8e6c9;"
        "font-size:7pt;color:#999;text-align:center}\n"
        "</style>\n"
    )


def _branded_header_html(logo_data_url: str, doctype_label: str, doc_number_expr: str) -> str:
    return (
        f'<div class="pf-head">\n'
        f'  <div class="pf-company">'
        f'<img src="{logo_data_url}" alt="Casa Moderna" class="pf-logo">'
        f'<div>'
        f'<div class="pf-company-name">Casa Moderna Ltd</div>'
        f'<div class="pf-company-addr">Mdina Road, Zebbug ZBG 9014, Malta</div>'
        f'<div class="pf-company-vat">VAT Reg No: MT29516422</div>'
        f'</div></div>\n'
        f'  <div class="pf-docbox">'
        f'<div class="pf-doctype">{doctype_label}</div>'
        f'<div class="pf-docno">{doc_number_expr}</div>'
        f'</div>\n'
        f'</div>\n'
    )


# ---------------------------------------------------------------------------
# Per-format transformations
# ---------------------------------------------------------------------------

def _upgrade_proforma(html: str, logo_data_url: str) -> str:
    """Replace leading <h3> with full branded header; keep body intact."""
    label = "Proforma"
    number = "{{ doc.cm_v1_operational_no or doc.cm_v1_draft_no or doc.name }}"
    header = _branded_header_css() + _branded_header_html(logo_data_url, label, number)
    # Strip the existing <h3>...</h3> opener
    new_html = re.sub(r"^<h3>[^<]*</h3>\s*", "", html, count=1)
    return header + new_html


def _upgrade_pos_invoice(html: str, logo_data_url: str) -> str:
    label = "POS Invoice"
    number = "{{ doc.cm_v1_operational_no or doc.cm_v1_draft_no or doc.name }}"
    header = _branded_header_css() + _branded_header_html(logo_data_url, label, number)
    new_html = re.sub(r"^<h3>[^<]*</h3>\s*", "", html, count=1)
    return header + new_html


def _upgrade_receipt(html: str, logo_data_url: str) -> str:
    label = "Receipt"
    number = "{{ doc.cm_v1_operational_no or doc.cm_v1_draft_no or doc.name }}"
    header = _branded_header_css() + _branded_header_html(logo_data_url, label, number)
    new_html = re.sub(r"^<h3>[^<]*</h3>\s*", "", html, count=1)
    return header + new_html


def _strip_logo_delivery_note(html: str) -> str:
    """Remove <img> from .pf-company block; keep company name text."""
    return re.sub(r"<img\b[^>]*/?>", "", html)


# Extra CSS classes needed for logo-based headers (appended to existing <style> block)
_LOGO_CSS_EXTRA = (
    ".pf-company{display:flex;align-items:center;gap:12px}\n"
    ".pf-logo{height:55px;max-width:190px;object-fit:contain}\n"
    ".pf-company-name{font-size:11pt;font-weight:700;color:#339966}\n"
    ".pf-company-addr{font-size:8pt;color:#555;margin-top:2px}\n"
    ".pf-company-vat{font-size:7.5pt;color:#888;margin-top:1px}\n"
)


def _upgrade_fixture_format(html: str, logo_data_url: str) -> str:
    """
    Upgrade QT/SO/SI templates generated by generate_print_formats.py:
    - Append logo CSS classes to the <style> block.
    - Replace the text brand block with a logo image block.
    - Fix the doc number to show V1 first, ERPNext name as fallback.
    """
    # 1. Append logo CSS before closing </style>
    if _LOGO_CSS_EXTRA.strip().split('\n')[0] not in html:
        html = html.replace("</style>", _LOGO_CSS_EXTRA + "</style>", 1)

    # 2. Replace text brand block with logo
    old_brand = (
        '<div>\n    <div class="pf-brand">casa moderna</div>\n'
        '    <div class="pf-brand-sub">{{ doc.company }}</div>\n  </div>'
    )
    new_company = (
        '<div class="pf-company">'
        f'<img src="{logo_data_url}" alt="Casa Moderna" class="pf-logo">'
        '<div>'
        '<div class="pf-company-name">Casa Moderna Ltd</div>'
        '<div class="pf-company-addr">Mdina Road, Zebbug ZBG 9014, Malta</div>'
        '<div class="pf-company-vat">VAT Reg No: MT29516422</div>'
        '</div></div>'
    )
    html = html.replace(old_brand, new_company, 1)

    # 3. Fix docno: show V1 operational/draft number as primary, ERPNext name as fallback
    old_docno = (
        '<div class="pf-docno">{{ doc.name }}</div>\n'
        '    {% if doc.cm_v1_draft_no %}<div class="pf-docmeta">V1 Draft: {{ doc.cm_v1_draft_no }}</div>{% endif %}\n'
        '    {% if doc.cm_v1_operational_no %}<div class="pf-docmeta">V1 Ref: {{ doc.cm_v1_operational_no }}</div>{% endif %}'
    )
    new_docno = '<div class="pf-docno">{{ doc.cm_v1_operational_no or doc.cm_v1_draft_no or doc.name }}</div>'
    html = html.replace(old_docno, new_docno, 1)

    return html


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

# Maps format name -> transformation function (logo_data_url passed as 2nd arg or None)
TRANSFORMS = {
    "CasaModerna Quotation":     (_upgrade_fixture_format,    True),
    "CasaModerna Sales Order":   (_upgrade_fixture_format,    True),
    "CasaModerna Sales Invoice": (_upgrade_fixture_format,    True),
    "CasaModerna Proforma":      (_upgrade_proforma,          True),
    "CasaModerna POS Invoice":   (_upgrade_pos_invoice,       True),
    "CasaModerna Receipt":       (_upgrade_receipt,           True),
    "CasaModerna Delivery Note": (_strip_logo_delivery_note,  False),
}


def execute():
    frappe.set_user("Administrator")
    logo_data_url = _logo_data_url()

    results = []
    for name, (fn, needs_logo) in TRANSFORMS.items():
        if not frappe.db.exists("Print Format", name):
            results.append({"name": name, "status": "not_found"})
            continue

        pf = frappe.get_doc("Print Format", name)
        if not pf.html:
            results.append({"name": name, "status": "no_html"})
            continue

        new_html = fn(pf.html, logo_data_url) if needs_logo else fn(pf.html)

        if new_html == pf.html:
            results.append({"name": name, "status": "no_change"})
        else:
            pf.html = new_html
            pf.save(ignore_permissions=True)
            results.append({"name": name, "status": "updated"})

    frappe.db.commit()
    return results
