"""voucher_api.py — CM Voucher business-logic API for the React DMS frontend.

All endpoints are decorated with ``@frappe.whitelist()`` and perform
server-side authentication/authorisation checks before any state mutation.

Workflow:
    Draft
      └─ submit_for_authorization()  →  Pending Authorization
            ├─ authorize_voucher()   →  Authorized (Voucher Authorizer role)
            └─ reject_voucher()      →  Rejected

    Authorized
      └─ redeem_voucher()            →  Redeemed
"""

from __future__ import annotations

import frappe
from frappe.utils import getdate, now_datetime, today

from casamoderna_dms.casamoderna_dms.doctype.cm_voucher.cm_voucher import (
    AUTHORIZER_ROLE,
    DEFAULT_VALIDITY_DAYS,
    NO_AUTH_SOURCES,
)


def _is_authorizer(user: str | None = None) -> bool:
    """Return True if the user holds the Voucher Authorizer role."""
    return AUTHORIZER_ROLE in frappe.get_roles(user)

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _require_login() -> str:
    """Return the current user or raise PermissionError for Guest."""
    user = frappe.session.user
    if not user or user == "Guest":
        frappe.throw("Authentication required.", frappe.PermissionError)
    return user


def _get_voucher(name: str):
    """Load a CM Voucher document (frappe.get_doc enforces read permission)."""
    return frappe.get_doc("CM Voucher", name)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


@frappe.whitelist()
def create_voucher(
    recipient_customer: str,
    voucher_value: float,
    valid_until: str = "",
    purchaser_customer: str = "",
    voucher_source: str = "Customer Purchase",
    notes: str = "",
) -> dict:
    """Create a new CM Voucher in Draft status.

    * Customer Purchase vouchers require a purchaser_customer.
    * Company-issued vouchers (Casa Moderna / Danzah) do not.
    * valid_until defaults to today + DEFAULT_VALIDITY_DAYS when omitted.
    The voucher code is auto-generated by the ``CMVoucher.before_insert`` hook.
    """
    _require_login()

    if not valid_until:
        from frappe.utils import add_days, today as _today
        valid_until = add_days(_today(), DEFAULT_VALIDITY_DAYS)

    doc = frappe.new_doc("CM Voucher")
    doc.voucher_source      = voucher_source or "Customer Purchase"
    doc.purchaser_customer  = purchaser_customer or ""
    doc.recipient_customer  = recipient_customer
    doc.voucher_value       = float(voucher_value)
    doc.valid_until         = valid_until
    doc.notes               = notes or ""
    doc.insert()
    frappe.db.commit()

    return {
        "name":         doc.name,
        "voucher_code": doc.voucher_code,
        "status":       doc.status,
    }


@frappe.whitelist()
def submit_for_authorization(voucher_name: str) -> dict:
    """Activate or submit a Draft voucher for authorization.

    * Customer Purchase vouchers are auto-authorized immediately (no human
      sign-off required — the customer has already paid).
    * Company-issued vouchers (Casa Moderna / Danzah) move to
      Pending Authorization where a Voucher Authorizer must approve.
    """
    _require_login()

    doc = _get_voucher(voucher_name)
    if doc.status != "Draft":
        frappe.throw(
            f"Only Draft vouchers can be activated. "
            f"Current status: {doc.status}.",
            frappe.ValidationError,
        )

    source = doc.voucher_source or "Customer Purchase"
    if source in NO_AUTH_SOURCES:
        # Customer has paid — activate immediately.
        doc.status = "Pending Authorization"  # validate() will flip to Authorized
    else:
        # Company-issued — requires Jason's sign-off.
        doc.status = "Pending Authorization"

    doc.save()
    frappe.db.commit()

    return {"voucher_name": doc.name, "status": doc.status}


@frappe.whitelist()
def authorize_voucher(voucher_name: str) -> dict:
    """Record an approval, transitioning the voucher to Authorized.

    Only users with the Voucher Authorizer role may call this endpoint.
    The document automatically transitions to Authorized via the
    ``CMVoucher._check_auto_authorize`` validate hook.
    """
    user = _require_login()

    if not _is_authorizer(user):
        frappe.throw(
            "Only users with the Voucher Authorizer role may approve vouchers.",
            frappe.PermissionError,
        )

    doc = _get_voucher(voucher_name)
    if doc.status != "Pending Authorization":
        frappe.throw(
            f"Only Pending Authorization vouchers can be approved. "
            f"Current status: {doc.status}.",
            frappe.ValidationError,
        )

    if doc.authorized_by_jason:
        frappe.throw(
            "Jason Falzon has already authorized this voucher.",
            frappe.ValidationError,
        )
    doc.authorized_by_jason = 1

    # validate() inside save() will auto-transition to Authorized.
    doc.save()
    frappe.db.commit()

    return {
        "voucher_name": doc.name,
        "status": doc.status,
        "authorized_by_jason": bool(doc.authorized_by_jason),
    }


@frappe.whitelist()
def reject_voucher(voucher_name: str, reason: str = "") -> dict:
    """Reject a Pending Authorization voucher (only Voucher Authorizers may reject)."""
    user = _require_login()

    if not _is_authorizer(user):
        frappe.throw(
            "Only users with the Voucher Authorizer role may reject vouchers.",
            frappe.PermissionError,
        )

    doc = _get_voucher(voucher_name)
    if doc.status != "Pending Authorization":
        frappe.throw(
            f"Only Pending Authorization vouchers can be rejected. "
            f"Current status: {doc.status}.",
            frappe.ValidationError,
        )

    doc.status = "Rejected"
    if reason:
        prefix = f"REJECTED by {user}: {reason.strip()}\n\n"
        doc.notes = (prefix + (doc.notes or "")).strip()

    doc.save()
    frappe.db.commit()

    return {"voucher_name": doc.name, "status": doc.status}


@frappe.whitelist()
def redeem_voucher(
    voucher_name: str,
    customer: str,
    amount: float,
    receipt_reference: str = "",
) -> dict:
    """Mark an Authorized voucher as Redeemed as a form of payment.

    The voucher is tied to a named customer account and cannot be transferred.
    ``customer`` must match the voucher's ``recipient_customer``.
    ``receipt_reference`` (optional) — the Sales Invoice, Cash Sale, or other
    receipt number where the voucher was applied as payment.
    """
    _require_login()

    doc = _get_voucher(voucher_name)
    if doc.status != "Authorized":
        frappe.throw(
            f"Only Authorized vouchers can be redeemed. "
            f"Current status: {doc.status}.",
            frappe.ValidationError,
        )

    # Expiry check
    if getdate(doc.valid_until) < getdate(today()):
        frappe.throw(
            "This voucher expired on "
            f"{frappe.format_date(doc.valid_until)} and cannot be redeemed.",
            frappe.ValidationError,
        )

    # Customer identity check — voucher cannot be transferred
    if doc.recipient_customer != customer:
        frappe.throw(
            "This voucher is issued to a different customer account and "
            "cannot be transferred or redeemed for cash.",
            frappe.PermissionError,
        )

    # Amount validation — server authoritative
    amount = float(amount)
    if amount <= 0:
        frappe.throw(
            "Redemption amount must be greater than zero.",
            frappe.ValidationError,
        )
    if amount > float(doc.voucher_value):
        frappe.throw(
            f"Redemption amount (€{amount:,.2f}) cannot exceed the "
            f"voucher face value (€{float(doc.voucher_value):,.2f}).",
            frappe.ValidationError,
        )

    doc.status = "Redeemed"
    doc.redeemed_amount = amount
    doc.redeemed_date = now_datetime()
    doc.redeemed_against_so = receipt_reference or ""
    doc.save()
    frappe.db.commit()

    return {
        "voucher_name":      doc.name,
        "status":            doc.status,
        "redeemed_amount":   amount,
        "redeemed_date":     str(doc.redeemed_date),
        "receipt_reference": doc.redeemed_against_so or "",
    }


@frappe.whitelist()
def get_voucher(voucher_name: str) -> dict:
    """Return a single CM Voucher document as a dict."""
    _require_login()
    doc = _get_voucher(voucher_name)
    return doc.as_dict()


@frappe.whitelist()
def get_voucher_list(
    status: str = "",
    purchaser_customer: str = "",
    recipient_customer: str = "",
    q: str = "",
    limit: int = 50,
) -> list[dict]:
    """Return a filtered list of CM Vouchers (respects Frappe permission layer)."""
    _require_login()

    filters = []
    if status:
        filters.append(["status", "=", status])
    if purchaser_customer:
        filters.append(["purchaser_customer", "=", purchaser_customer])
    if recipient_customer:
        filters.append(["recipient_customer", "=", recipient_customer])

    or_filters = []
    if q:
        q_like = f"%{q}%"
        or_filters = [
            ["voucher_code", "like", q_like],
            ["purchaser_name", "like", q_like],
            ["recipient_name", "like", q_like],
        ]

    fields = [
        "name",
        "voucher_code",
        "status",
        "voucher_source",
        "purchaser_customer",
        "purchaser_name",
        "recipient_customer",
        "recipient_name",
        "voucher_value",
        "valid_until",
        "authorized_by_jason",
        "redeemed_amount",
        "redeemed_date",
        "redeemed_against_so",
        "modified",
        "creation",
    ]

    return frappe.get_list(
        "CM Voucher",
        fields=fields,
        filters=filters,
        or_filters=or_filters if or_filters else None,
        limit_page_length=int(limit),
        order_by="modified desc",
    )


@frappe.whitelist()
def get_voucher_history(voucher_name: str) -> list[dict]:
    """Return the change history for a CM Voucher from the Frappe Version table.

    Each entry contains:
        creation  — ISO datetime of the change
        owner     — Frappe user who made the change
        changed   — list of {field, from, to} dicts for the fields that changed
    """
    import json as _json

    _require_login()

    versions = frappe.db.sql(
        """
        SELECT
            v.creation,
            v.owner,
            v.data
        FROM `tabVersion` v
        WHERE v.ref_doctype = 'CM Voucher'
          AND v.docname      = %(name)s
        ORDER BY v.creation ASC
        """,
        {"name": voucher_name},
        as_dict=True,
    )

    result = []
    for row in versions:
        raw = row.get("data") or "{}"
        try:
            data = _json.loads(raw)
        except Exception:
            data = {}

        changed = []
        for item in data.get("changed", []):
            # Frappe stores [fieldname, old_value, new_value]
            if isinstance(item, (list, tuple)) and len(item) >= 3:
                changed.append({"field": item[0], "from": item[1], "to": item[2]})

        result.append(
            {
                "creation": str(row.creation),
                "owner": row.owner,
                "changed": changed,
            }
        )

    return result


@frappe.whitelist()
def get_pending_authorizations() -> list[dict]:
    """Return all vouchers in Pending Authorization status with full detail.

    Intended for the dedicated Approvals screen used by Voucher Authorizers.
    Any authenticated user with read permission on CM Voucher can call this;
    the action endpoints still enforce the authorizer check.
    """
    _require_login()

    return frappe.get_list(
        "CM Voucher",
        fields=[
            "name",
            "voucher_code",
            "status",
            "voucher_source",
            "purchaser_customer",
            "purchaser_name",
            "recipient_customer",
            "recipient_name",
            "voucher_value",
            "valid_until",
            "authorized_by_jason",
            "notes",
            "creation",
            "owner",
            "modified",
            "modified_by",
        ],
        filters=[
            ["status", "=", "Pending Authorization"],
            ["voucher_source", "!=", "Customer Purchase"],
        ],
        order_by="creation asc",
        limit_page_length=500,
    )


# ---------------------------------------------------------------------------
# Payment / redemption by code
# ---------------------------------------------------------------------------

def _lookup_by_code(voucher_code: str):
    """Find a CM Voucher document by its printed code (strips dashes/spaces)."""
    clean = voucher_code.replace("-", "").replace(" ", "").upper()
    name = frappe.db.get_value("CM Voucher", {"voucher_code": clean}, "name")
    if not name:
        frappe.throw(
            f"No voucher found with code '{voucher_code}'. "
            "Please check the code and try again.",
            frappe.DoesNotExistError,
        )
    return frappe.get_doc("CM Voucher", name)


@frappe.whitelist()
def validate_voucher_for_payment(
    voucher_code: str,
    customer: str = "",
    amount: float = 0,
) -> dict:
    """Look up a voucher by its printed code and validate it for use as payment.

    Returns the voucher details if valid; raises a descriptive error if not.
    This is a read-only check — no state changes are made.

    If ``customer`` is provided the voucher's ``recipient_customer`` must match;
    a clear error is raised if it belongs to a different customer account.
    """
    _require_login()

    doc = _lookup_by_code(voucher_code)

    if doc.status != "Authorized":
        frappe.throw(
            f"This voucher is not available for payment. Current status: {doc.status}.",
            frappe.ValidationError,
        )

    if getdate(doc.valid_until) < getdate(today()):
        frappe.throw(
            f"This voucher expired on {frappe.format_date(doc.valid_until)} "
            "and can no longer be used.",
            frappe.ValidationError,
        )

    if customer and doc.recipient_customer != customer:
        frappe.throw(
            "This voucher belongs to a different customer account. "
            "Gift vouchers cannot be transferred or redeemed for cash.",
            frappe.PermissionError,
        )

    if amount and float(amount) > float(doc.voucher_value):
        frappe.throw(
            f"Payment amount (€{float(amount):,.2f}) exceeds the voucher "
            f"face value (€{float(doc.voucher_value):,.2f}).",
            frappe.ValidationError,
        )

    from frappe.utils import date_diff
    days_left = date_diff(doc.valid_until, today())

    return {
        "name":               doc.name,
        "voucher_code":       doc.voucher_code,
        "voucher_source":     doc.voucher_source or "Customer Purchase",
        "voucher_value":      doc.voucher_value,
        "valid_until":        str(doc.valid_until),
        "days_remaining":     days_left,
        "status":             doc.status,
        "recipient_customer": doc.recipient_customer,
        "recipient_name":     doc.recipient_name or "",
        "purchaser_customer": doc.purchaser_customer or "",
        "purchaser_name":     doc.purchaser_name or "",
    }


@frappe.whitelist()
def redeem_voucher_by_code(
    voucher_code: str,
    customer: str,
    amount: float,
    receipt_reference: str = "",
) -> dict:
    """DEPRECATED — does not create a Payment Entry. Use redeem_voucher_by_code_with_pe instead."""
    frappe.throw(
        "redeem_voucher_by_code is disabled. Use redeem_voucher_by_code_with_pe to create a "
        "Payment Entry so the redemption appears in the Receipts list.",
        frappe.ValidationError,
    )


@frappe.whitelist()
def redeem_voucher_by_code_with_pe(
    voucher_code: str,
    customer: str,
    amount: float,
    party_name: str = "",
    posting_date: str = "",
) -> dict:
    """Redeem a voucher by code AND create a submitted Payment Entry in one call.

    Creates a Payment Entry (payment_type=Receive, mode_of_payment=Gift Voucher,
    paid_to=Gift Vouchers - CM) so that the transaction appears in the Receipts
    list alongside cash/card/bank payments.

    Returns a dict with both ``pe_name`` and voucher redemption fields.
    """
    _require_login()

    # ── 1. Validate everything before any writes ──────────────────────────────
    voucher_doc = _lookup_by_code(voucher_code)
    amount = float(amount)

    if voucher_doc.status != "Authorized":
        frappe.throw(
            f"Only Authorized vouchers can be redeemed. "
            f"Current status: {voucher_doc.status}.",
            frappe.ValidationError,
        )
    if getdate(voucher_doc.valid_until) < getdate(today()):
        frappe.throw(
            f"This voucher expired on {frappe.format_date(voucher_doc.valid_until)}.",
            frappe.ValidationError,
        )
    if voucher_doc.recipient_customer != customer:
        frappe.throw(
            "This voucher is issued to a different customer account.",
            frappe.PermissionError,
        )
    if amount <= 0:
        frappe.throw("Redemption amount must be greater than zero.", frappe.ValidationError)
    if amount > float(voucher_doc.voucher_value):
        frappe.throw(
            f"Redemption amount (€{amount:,.2f}) exceeds voucher value "
            f"(€{float(voucher_doc.voucher_value):,.2f}).",
            frappe.ValidationError,
        )

    pdate = posting_date or today()

    # ── 2. Create and submit the Payment Entry ────────────────────────────────
    pe = frappe.get_doc({
        "doctype":                    "Payment Entry",
        "naming_series":              "PE .######",
        "company":                    "Casa Moderna Limited",
        "payment_type":               "Receive",
        "party_type":                 "Customer",
        "party":                      customer,
        "party_name":                 party_name or customer,
        "paid_amount":                amount,
        "received_amount":            amount,
        "base_paid_amount":           amount,
        "base_received_amount":       amount,
        "source_exchange_rate":       1,
        "target_exchange_rate":       1,
        "mode_of_payment":            "Gift Voucher",
        "paid_from":                  "Debtors - CM",
        "paid_from_account_currency": "EUR",
        "paid_to":                    "Gift Vouchers - CM",
        "paid_to_account_currency":   "EUR",
        "reference_no":               pdate,
        "reference_date":             pdate,
        "posting_date":               pdate,
        "remarks":                    f"Gift Voucher redemption — code: {voucher_code}",
    })
    pe.insert(ignore_permissions=True)
    pe.submit()

    # ── 3. Mark voucher as Redeemed, record PE name as reference ─────────────
    voucher_doc.status = "Redeemed"
    voucher_doc.redeemed_amount = amount
    voucher_doc.redeemed_date = now_datetime()
    voucher_doc.redeemed_against_so = pe.name
    voucher_doc.save()
    frappe.db.commit()

    return {
        "pe_name":           pe.name,
        "voucher_name":      voucher_doc.name,
        "status":            voucher_doc.status,
        "redeemed_amount":   amount,
        "redeemed_date":     str(voucher_doc.redeemed_date),
        "receipt_reference": pe.name,
    }
